name: security

on:
  workflow_dispatch: 

permissions:
  actions: read
  security-events: write
  contents: read

jobs:
  dependencies-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: run osv-scanner
        uses: google/osv-scanner-action/osv-scanner-action@daa2c68f50d845057895a9c300e42478481c1d26
        with:
          scan-args: |-
            --format sarif
            --output DependenciesAnalysisFull.sarif
            ./
        continue-on-error: true

      - name: Upload OSV report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: DependenciesAnalysisFull.sarif

  source-code-analysis:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: run semgrep
        run: semgrep scan --config=auto --sarif --output=semgrep.sarif .src

      - name: Upload Semgrep report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
